### ISSUE TITLE
capture not working

### ISSUE THREAD

**Issue by yhan0410** [tanjeffreyz02/auto-maple#22]
I am running it on VM (parallels) and only use CPU for tensorflow.
log:
Started video capture.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xx\Downloads\auto-maple-1.0.1\capture.py", line 41, in _main
    with mss.mss() as sct:
AttributeError: __enter__

Could you give some hints on where is the problem

**Comment by tanjeffreyz02** [comment]
Hi, sorry for the late reply! I'm not too sure what is causing this since the AttributeError is from Python's with statement. Could you please try reinstalling the mss library by running ```python -m pip install -U --user mss```? Also, please make sure there is an import statement at the top of capture.py that says ```from mss import mss``` , not just ```import mss```?
