### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by s58314** [tanjeffreyz02/auto-maple#24]
Started main bot loop.

Initializing detection algorithm...

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\auto-maple\bot.py", line 123, in _main
    model = detection.load_model()
  File "C:\auto-maple\detection.py", line 19, in load_model
    return tf.saved_model.load(model_dir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\load.py", line 900, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\load.py", line 913, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 60, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 118, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: assets/models/rune_model_rnn_filtered_cannied/saved_model\{saved_model.pbtxt|saved_model.pb}

**Comment by bkkwok** [comment]
do you have the model saved in assets? If not download from link below, and place it in assets.
https://drive.google.com/drive/folders/1SPdTNF4KZczoWyWTgfyTBRvLvy7WSGpu
